### ISSUE TITLE
Translations for different languages in the config file

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#17]
`config.py` uses the TOML format to allow users to customise the output they receive from the CLI tool.''

Please add your language for each theme

**Comment by rexdivakar** [comment]
Do u have any suggestions on how to proceed so i can take this up too

**Comment by TechWiz-3** [comment]
I'd recommend copying the english locale and then pasting it below editing it to reflect the same words but in your chosen language

**Comment by TechWiz-3** [comment]
One thing at a time tho 😆

**Comment by ShivanshDengla** [comment]
Hey,
I made a pull request, I updated for Hindi, but i am doing this for the first time so i didn't know how to correctly code it. I just copied english and changed the Hindi lines, do let me know if theres any mistake, i'll try to correct it.
Thanks

**Comment by TechWiz-3** [comment]
Perfect, I'll check it out and let you know 👍

**Comment by IamMU** [comment]
I can do german translation

**Comment by kat-kan** [comment]
I can do Polish translation if you want :)

**Comment by TechWiz-3** [comment]
Great :))

**Comment by ethmtrgt** [comment]
Hello, I can do Turkish translation.

**Comment by TechWiz-3** [comment]
Perfect

**Comment by shubham7668** [comment]
> Perfect

Hey @TechWiz-3 i have added french language support

**Comment by TechWiz-3** [comment]
Merci becoup 🤣

**Comment by shubham7668** [comment]
> Merci becoup 🤣

C'est mon plaisir 🤗

**Comment by rexdivakar** [comment]
Hey @TechWiz-3 i have added for tamil translation, kindly review and approve the PR #35

**Comment by Sir1Code** [comment]
I'd love to make a Hebrew translation :)

**Comment by chrisli-03** [comment]
i can translate to Chinese

**Comment by TechWiz-3** [comment]
Go ahead :)

**Comment by Lakhaninawaz** [comment]
> Go ahead :)

Hello,  i am first time in contrubution please help me how can do it

**Comment by TechWiz-3** [comment]
Sure man are you familiar with git?

**Comment by Lakhaninawaz** [comment]
yes, I know little about Git. But i know about Github.

**Comment by TechWiz-3** [comment]
1. Fork the repository
2. Clone your fork
3. Go into your fork and open a text editor for the file `unfollow/unfollow/config.py`
4. Copy this text
```toml

[locale.english.simple]
welcome_message = "Welcome to who-unfollowed-me Python implementation by Zac the Wise"
fetched_followers_message = "Fetched github followers"
no_unfollows_message = "No unfollows!"
end_message = "You have {follower_num} followers. Keep up the good work\\n"
thankyou_message = "Thanks for using this project"
[locale.english.regular]
welcome_message = ":dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]"
fetched_followers_message = "[green]✔ [underline]Fetched github followers"
last_week_unfollowers = "[purple]✔ [underline]Unfollowers from last week"
no_unfollows_message = "[green]:raised_hands: [underline]No unfollows!"
end_message = ":fire: You have {follower_num} followers. Keep up the good work\\n"
thankyou_message = ":pray: Thanks for using this project"
[locale.english.panels]
welcome_message = ":dancer: [purple]Welcome to[/purple] [red]who-unfollowed-me[/red][blue] Python implementation[/blue] by [#FFD700]Zac the Wise[#FFD700]"
fetched_followers_message = "[green]✔ [underline]Fetched github followers"
last_week_unfollowers = "[purple]✔ [underline]Unfollowers from last week"
no_unfollows_message = "[white on #308012] No unfollows! [/white on #308012]                                "
end_message = ":fire: You have {follower_num} followers. Keep up the good work\\n"
thankyou_message = ":pray: Thanks for using this project"
[locale.english.bubbles]
welcome_message_a = "[white on purple]Welcome to[/white on purple]"
welcome_message_b = "[white on red]who-unfollowed-me[/white on red]"
welcome_message_c = "[white on blue]the Python implementation[/white on blue]"
welcome_message_d = "[white on dark_goldenrod]by Zac the Wise[/white on dark_goldenrod]"
fetched_followers_message = "[white on cyan]Fetched github followers[/white on cyan]"
last_week_unfollowers = "[purple]✔ [underline]Unfollowers from last week"
no_unfollows_message = "[white on green4]No unfollows![/white on green4]"
end_message_a = "[white on purple]You have {follower_num} followers.[/white on purple]"
end_message_b = "[white on magenta]Keep up the good work![/white on magenta]"
thankyou_message = "[white on blue]Thanks for using this project[/white on blue]"
```
5. Copy this to the bottom of the Toml section which is currently line 366. Change the word English in each heading to the english name of your language e.g. `[locale.hindi.bubbles]` or `[locale.arabic.bubbles]` etc
6. Edit the text to be in your language
7. Push the changes to your repo
8. Open a pull request, name it `Add [your language] translation #17`
9. Submit :)
